#!/usr/bin/env python3
"""Generate the StillPoint help vault content."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil


@dataclass(frozen=True)
class HelpPage:
    name: str
    title: str
    content: str


def _page(path: str) -> str:
    return f"{path}/{path}.md"


def _page_to_colon(page: str) -> str:
    cleaned = page[:-3] if page.endswith(".md") else page
    parts = [part for part in cleaned.split("/") if part]
    if len(parts) >= 2 and parts[-1] == parts[-2]:
        parts = parts[:-1]
    return ":".join(parts)


def _toc_entry(title: str, page: str, description: str) -> str:
    colon = _page_to_colon(page)
    return f"- [:{colon}|{title}] - {description}"


def _build_pages() -> list[HelpPage]:
    pages: list[HelpPage] = []

    welcome_links = [
        _toc_entry("Getting Started", _page("Getting-Started"), "Create/open vaults and learn the basics."),
        _toc_entry("Navigation", _page("Navigation"), "Move through your vault and locate content quickly."),
        _toc_entry("Editor", _page("Editor"), "Write, link, and structure your notes."),
        _toc_entry("Tasks", _page("Tasks"), "Track and manage to-dos."),
        _toc_entry("Calendar", _page("Calendar"), "Journal navigation and date browsing."),
        _toc_entry("Attachments", _page("Attachments"), "Add files and media to pages."),
        _toc_entry("Remote Vaults", _page("Remote-Vaults"), "Access vaults from a server across devices."),
        _toc_entry("Modes", _page("Modes"), "VI, Focus, and Audience modes for different workflows."),
        _toc_entry("Rendering", _page("Rendering"), "PlantUML and Mermaid diagram rendering."),
        _toc_entry("AI", _page("AI"), "Optional AI features and workflows."),
        _toc_entry("Web Client", _page("Web-Client"), "Access your vault in a browser."),
        _toc_entry("Shortcuts", _page("Shortcuts"), "Speed up common actions."),
        _toc_entry("Preferences", _page("Preferences"), "Global and vault-specific settings."),
        _toc_entry("Troubleshooting", _page("Troubleshooting"), "Fix common issues."),
    ]
    pages.append(
        HelpPage(
            name=_page("Welcome"),
            title="Welcome to StillPoint",
            content="\n".join(
                [
                    "# Welcome to StillPoint",
                    "",
                    "StillPoint stores knowledge as pages inside a vault folder on disk.",
                    "This help vault explains the main areas of the app and how they fit together.",
                    "",
                    "## How to Use This Help Vault",
                    "- Each topic is a page (folder/page).",
                    "- Links use colon notation, like `:Navigation` or `:Tasks`.",
                    "- Use the Command Bar (Ctrl+Shift+P) to jump to any help page.",
                    "",
                    "## Quick Tour",
                    "- Vaults are folders of pages stored on disk.",
                    "- Pages are Markdown files organized as `Page/Page.md`.",
                    "- Left sidebar: Vault tree, Tags, Search.",
                    "- Center: the editor.",
                    "- Right sidebar: Tasks, Calendar, Attachments, Link Navigator.",
                    "",
                    "## Start Here",
                    "- [:Getting-Started|Getting Started] - open a vault and create your first page.",
                    "- [:Navigation|Navigation] - learn the tree, tags, search, and links.",
                    "- [:Editor|Editor] - write, link, and format content.",
                    "",
                    "## Help Topics",
                    *welcome_links,
                    "",
                    "## Example Link",
                    "To open the navigation guide, use a colon link:",
                    "```",
                    "[:Navigation|Navigation]",
                    ":Navigation",
                    "```",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Getting-Started"),
            title="Getting Started",
            content="\n".join(
                [
                    "# Getting Started",
                    "",
                    "## First Time Setup",
                    "When you first run StillPoint, you'll see a welcome screen.",
                    "- Click 'Create New Vault' to start fresh.",
                    "- Or 'Open Existing Vault' to use an existing folder.",
                    "- Vaults are just folders on your computer with Markdown files.",
                    "",
                    "## Create or Open a Vault",
                    "- Use Vault -> New Vault to create a new vault.",
                    "- Use Vault -> Open Vault in New Window to open a different vault.",
                    "- If Remote Vaults are enabled, choose a remote vault from the Open Vault dialog.",
                    "",
                    "## Vault Structure",
                    "StillPoint stores pages in matching folders.",
                    "Example structure:",
                    "```",
                    "MyNotes/",
                    "  MyNotes.md",
                    "  Projects/",
                    "    Projects.md",
                    "    Website/",
                    "      Website.md",
                    "```",
                    "",
                    "## Core Layout",
                    "- Left sidebar: Vault tree, Tags, Search.",
                    "- Center: Editor.",
                    "- Right sidebar: Tasks, Calendar, Attachments, Link Navigator.",
                    "",
                    "## First Page",
                    "- Use File -> New Page to create a note.",
                    "- Pages live as Markdown files on disk.",
                    "Example page content:",
                    "```markdown",
                    "# My First Page",
                    "",
                    "This is a simple note.",
                    "",
                    "- [ ] Task 1",
                    "- [x] Task 2 (done)",
                    "",
                    "Link to another page: :AnotherPage",
                    "```",
                    "",
                    "## Saving",
                    "- StillPoint saves automatically as you type.",
                    "- Use Ctrl+S to force a save at any time.",
                    "",
                    "## Switching Vaults",
                    "- Use Vault -> Open Vault in New Window to work in multiple vaults at once.",
                    "",
                    "## Next Steps",
                    "- Learn about [:Editor|editing] and [:Navigation|navigation].",
                    "- Try adding [:Tasks|tasks] and [:Calendar|journal entries].",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Editor"),
            title="Editor",
            content="\n".join(
                [
                    "# Editor",
                    "",
                    "## Markdown Basics",
                    "StillPoint uses Markdown for formatting. It's simple text with special symbols.",
                    "",
                    "### Headings",
                    "- `#` for main title",
                    "- `##` for sections",
                    "- `###` for subsections",
                    "",
                    "### Text Formatting",
                    "- `*italic*` or `_italic_`",
                    "- `**bold**` or `__bold__`",
                    "- `` `code` `` for inline code",
                    "",
                    "### Lists",
                    "- `-` for bullets",
                    "- `1.` for numbered lists",
                    "",
                    "### Links",
                    "- `[text](url)` for external links",
                    "- `:PageName` for internal pages",
                    "- `[:PageName|Display Text]` for custom link text",
                    "",
                    "### Code Blocks",
                    "```language",
                    "code here",
                    "```",
                    "",
                    "## Writing in the Editor",
                    "- Type normally - StillPoint saves as you go.",
                    "- Use Ctrl+L to insert links quickly.",
                    "- Press F12 to toggle task checkboxes.",
                    "",
                    "## Tasks in Notes",
                    "- Use `- [ ]` for open tasks",
                    "- Use `- [x]` for completed tasks",
                    "Example:",
                    "```markdown",
                    "# Meeting Notes",
                    "",
                    "## Agenda",
                    "1. Review budget",
                    "2. Plan next sprint",
                    "",
                    "- [ ] Send calendar invite",
                    "- [x] Book conference room",
                    "```",
                    "",
                    "## Find & Replace",
                    "- Ctrl+F to find text in the current page.",
                    "- Ctrl+H to replace text.",
                    "- Search is case-insensitive.",
                    "",
                    "## Auto-Save",
                    "- Your work saves automatically.",
                    "- No need to worry about losing changes.",
                    "",
                    "## Tips for New Users",
                    "- Start with simple notes and build up.",
                    "- Use headings to organize your thoughts.",
                    "- Link related pages together.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Navigation"),
            title="Navigation",
            content="\n".join(
                [
                    "# Navigation",
                    "",
                    "## Vault Tree",
                    "The left sidebar shows your vault's folder structure.",
                    "- Click a page name to open it in the editor.",
                    "- Expand/collapse folders with the arrow icons.",
                    "- Right-click for more options like rename or delete.",
                    "",
                    "## Tags",
                    "Tags help group related pages.",
                    "- Add tags in your notes with `@tagname` or `#tagname`.",
                    "- Click a tag in the Tags panel to see all pages with that tag.",
                    "- Use tags to organize by project, topic, or status.",
                    "Example:",
                    "```markdown",
                    "# Project Plan",
                    "",
                    "Status: @active #project",
                    "",
                    "- [ ] Research phase",
                    "- [ ] Design phase",
                    "```",
                    "",
                    "## Search",
                    "Find anything in your vault quickly.",
                    "- Type in the Search box to scan all pages.",
                    "- Search looks in page titles and content.",
                    "- Use quotes for exact phrases: `\"project plan\"`",
                    "- Results show matching pages with snippets.",
                    "",
                    "## Link Navigator",
                    "Explore connections between pages.",
                    "- Shows a graph of how pages link to each other.",
                    "- Backlinks show which pages reference the current page.",
                    "- Click nodes to navigate, drag to rearrange.",
                    "",
                    "## Command Bar",
                    "Quick access to everything.",
                    "- Press Ctrl+Shift+P to open.",
                    "- Type to search pages, commands, or settings.",
                    "- Examples: type \"new page\" or \"preferences\".",
                    "",
                    "## History",
                    "- Alt+Left/Right to go back/forward.",
                    "- Alt+Home to return to your home page.",
                    "",
                    "## Tips",
                    "- Use the vault tree for browsing.",
                    "- Use search for finding specific content.",
                    "- Use tags for ongoing projects.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Tasks"),
            title="Tasks",
            content="\n".join(
                [
                    "# Tasks",
                    "",
                    "## What Are Tasks?",
                    "Tasks are checkboxes in your Markdown notes.",
                    "- They help track to-dos alongside your regular notes.",
                    "- No separate task app needed - tasks live with your content.",
                    "",
                    "## Task Syntax",
                    "- `- [ ]` for open tasks",
                    "- `- [x]` for completed tasks",
                    "Example:",
                    "```markdown",
                    "# Project Tasks",
                    "",
                    "- [ ] Research competitors",
                    "- [x] Set up meeting",
                    "- [ ] Write report",
                    "```",
                    "",
                    "## Task Panel",
                    "The Tasks panel shows all tasks from your vault.",
                    "- Click a task to jump to its page.",
                    "- Double-click to toggle completion.",
                    "- Use the search box to filter tasks.",
                    "",
                    "## Filtering Tasks",
                    "- Type keywords to find specific tasks.",
                    "- Use tags like `@work` or `@personal`.",
                    "- Add dates like `2025-01-15` for scheduling.",
                    "Example filters:",
                    "- `@work` - show work-related tasks",
                    "- `meeting` - show tasks mentioning meetings",
                    "",
                    "## Actionable Tasks",
                    "The 'Show tasks you can act on now' toggle hides:",
                    "- Completed tasks",
                    "- Tasks with unfinished subtasks",
                    "- Tasks marked as non-actionable (like @wait)",
                    "",
                    "## Organizing Tasks",
                    "- Group related tasks under headings.",
                    "- Use tags for categories.",
                    "- Create separate pages for big projects.",
                    "",
                    "## Tips",
                    "- Keep tasks near the notes they relate to.",
                    "- Review your task list daily.",
                    "- Use dates for time-sensitive items.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Calendar"),
            title="Calendar",
            content="\n".join(
                [
                    "# Calendar",
                    "",
                    "## What Is the Calendar?",
                    "The Calendar panel shows dates mentioned in your notes.",
                    "- It scans your vault for dates in YYYY-MM-DD format.",
                    "- Click any date to see notes for that day.",
                    "- Double-click to create a new note for that date.",
                    "",
                    "## Date Formats",
                    "The calendar recognizes these formats:",
                    "- `2025-01-15` - full date",
                    "- `2025-01` - month only",
                    "- `2025` - year only",
                    "",
                    "## Viewing Notes by Date",
                    "- Click a date in the calendar to see all notes mentioning it.",
                    "- The list shows page titles and snippets.",
                    "- Click a page to open it in the editor.",
                    "",
                    "## Creating Dated Notes",
                    "- Double-click a date to create a new page.",
                    "- The page will be named with the date (e.g., `2025-01-15`).",
                    "- Add your notes, tasks, or journal entries.",
                    "",
                    "## Journaling",
                    "Use the calendar for daily journaling:",
                    "- Double-click today's date.",
                    "- Write about your day, thoughts, or plans.",
                    "- The calendar will show your journal entries over time.",
                    "",
                    "## Tips",
                    "- Add dates to tasks for scheduling.",
                    "- Use the calendar to review past notes.",
                    "- Combine with tasks for time management.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Attachments"),
            title="Attachments",
            content="\n".join(
                [
                    "# Attachments",
                    "",
                    "## Files",
                    "- Drag and drop files into the editor to attach.",
                    "- Attachments appear in the Attachments panel.",
                    "- Use the panel to open, rename, or remove attachments.",
                    "",
                    "## Images",
                    "- Images can be embedded inline in a page.",
                    "- Use attachments to keep large files organized.",
                    "",
                    "Example:",
                    "```markdown",
                    "![Screenshot](attachments/screenshot.png)",
                    "```",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("AI"),
            title="AI",
            content="\n".join(
                [
                    "# AI",
                    "",
                    "## What Is AI in StillPoint?",
                    "AI features help you work with your notes more efficiently.",
                    "- Summarize long pages or sections.",
                    "- Extract tasks from meeting notes.",
                    "- Generate outlines or drafts.",
                    "- Ask questions about your vault content.",
                    "",
                    "## AI Chat Panel",
                    "The AI Chat panel provides conversational AI assistance:",
                    "- Click the AI tab to open the chat.",
                    "- Ask questions about your notes.",
                    "- Request summaries or explanations.",
                    "- Get help with writing or editing.",
                    "",
                    "## AI Actions",
                    "Use the command bar (Ctrl+Shift+P) for AI actions:",
                    "- 'AI: Summarize Page' - create a summary of the current page.",
                    "- 'AI: Extract Tasks' - find and list tasks from text.",
                    "- 'AI: Generate Outline' - create a structure for your content.",
                    "- 'AI: Rewrite Section' - improve or rephrase text.",
                    "",
                    "## Getting Started with AI",
                    "1. Enable AI in Preferences (under AI section).",
                    "2. Choose your AI provider (OpenAI, Anthropic, etc.).",
                    "3. Add your API key.",
                    "4. Open the AI Chat panel to start chatting.",
                    "",
                    "## Privacy Considerations",
                    "- AI requests may send your note content to external services.",
                    "- Review your provider's privacy policy.",
                    "- You can disable AI features per vault.",
                    "- Content is not stored permanently by default.",
                    "",
                    "## Tips",
                    "- Use AI to brainstorm ideas for new pages.",
                    "- Ask AI to help organize scattered thoughts.",
                    "- Request help with formatting or structure.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Shortcuts"),
            title="Shortcuts",
            content="\n".join(
                [
                    "# Shortcuts",
                    "",
                    "## Essential Shortcuts",
                    "These shortcuts will speed up your workflow:",
                    "",
                    "### File Operations",
                    "- `Ctrl+S`: Save the current page",
                    "- `Ctrl+N`: Create a new page",
                    "- `Ctrl+O`: Open a page (jump to page)",
                    "- `Ctrl+Shift+S`: Save all open pages",
                    "",
                    "### Editing",
                    "- `Ctrl+Z`: Undo",
                    "- `Ctrl+Y`: Redo",
                    "- `Ctrl+X`: Cut",
                    "- `Ctrl+C`: Copy",
                    "- `Ctrl+V`: Paste",
                    "- `Ctrl+A`: Select all",
                    "- `Ctrl+F`: Find in page",
                    "- `Ctrl+H`: Replace in page",
                    "",
                    "### Navigation",
                    "- `Alt+Left`: Go back",
                    "- `Alt+Right`: Go forward",
                    "- `Alt+Home`: Go to home page",
                    "- `Ctrl+Shift+P`: Open command bar",
                    "- `Ctrl+L`: Insert link",
                    "- `Ctrl+Shift+L`: Insert link to new page",
                    "",
                    "### Tasks",
                    "- `F12`: Toggle task completion",
                    "- `Ctrl+\\`: Focus tasks search",
                    "",
                    "### Panels",
                    "- `Ctrl+Shift+Space`: Cycle focus between panels",
                    "- `F11`: Toggle fullscreen",
                    "",
                    "### Special",
                    "- `Alt+D`: Open today's journal page",
                    "- `Ctrl+.`: Open preferences",
                    "- `Ctrl+Shift+F`: Search across all pages",
                    "",
                    "## VI Mode Shortcuts",
                    "If VI mode is enabled:",
                    "- `Esc`: Enter command mode",
                    "- `i`: Enter insert mode",
                    "- `:`: Enter command line",
                    "- `h/j/k/l`: Navigate (left/down/up/right)",
                    "",
                    "## Tips",
                    "- Use the command bar (Ctrl+Shift+P) to discover more actions.",
                    "- Shortcuts can be customized in Preferences.",
                    "- Practice a few shortcuts daily to build muscle memory.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Preferences"),
            title="Preferences",
            content="\n".join(
                [
                    "# Preferences",
                    "",
                    "## Opening Preferences",
                    "Access preferences in two ways:",
                    "- Press `Ctrl+.` (control + period)",
                    "- Use the menu: Edit → Preferences",
                    "",
                    "## Global vs Vault Preferences",
                    "There are two levels of preferences:",
                    "- **Global Preferences**: Apply to all vaults",
                    "- **Vault Preferences**: Override settings for specific vaults",
                    "",
                    "## Key Settings",
                    "",
                    "### Appearance",
                    "- **Font**: Choose your preferred font and size",
                    "- **Theme**: Light or dark mode",
                    "- **Line Numbers**: Show/hide line numbers in editor",
                    "",
                    "### Features",
                    "- **Tasks Panel**: Enable/disable task tracking",
                    "- **Calendar Panel**: Enable/disable calendar view",
                    "- **AI Chat**: Enable/disable AI features",
                    "- **Remote Vaults**: Enable/disable server-backed vaults",
                    "- **VI Mode**: Enable VI-style editing",
                    "",
                    "### Editor",
                    "- **Auto-save**: Save changes automatically",
                    "- **Word Wrap**: Wrap long lines",
                    "- **Spell Check**: Enable spell checking",
                    "",
                    "### AI Settings",
                    "- **Provider**: Choose OpenAI, Anthropic, or other",
                    "- **API Key**: Enter your API key securely",
                    "- **Model**: Select the AI model to use",
                    "",
                    "## Vault-Specific Settings",
                    "To customize settings for one vault:",
                    "1. Open the vault",
                    "2. Go to Vault → Vault Preferences",
                    "3. Change settings as needed",
                    "4. Settings are saved per vault",
                    "",
                    "## Resetting Preferences",
                    "- To reset global preferences: Edit the config file manually",
                    "- To reset vault preferences: Choose 'Use Global Defaults'",
                    "",
                    "## Tips",
                    "- Experiment with different fonts for readability.",
                    "- Disable unused features to reduce clutter.",
                    "- Use vault preferences for different workflows.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Troubleshooting"),
            title="Troubleshooting",
            content="\n".join(
                [
                    "# Troubleshooting",
                    "",
                    "## Common Issues",
                    "",
                    "### Pages Not Appearing",
                    "- **Problem**: New pages don't show in navigation",
                    "- **Solution**: Go to Vault → Rebuild Vault Index",
                    "- **Prevention**: The index rebuilds automatically, but manual rebuild helps",
                    "",
                    "### Search Not Working",
                    "- **Problem**: Can't find pages or content",
                    "- **Solution**: Tools → Rebuild Search Index",
                    "- **Note**: Large vaults may take several minutes to index",
                    "",
                    "### Slow Performance",
                    "- **Problem**: App feels sluggish",
                    "- **Solutions**:",
                    "  - Close unused windows",
                    "  - Enable lazy loading in preferences",
                    "  - Reduce number of open tabs",
                    "  - Check for large attachments",
                    "",
                    "### Links Not Working",
                    "- **Problem**: Clicking links doesn't navigate",
                    "- **Solution**: Use Vault → Rebuild Vault Index",
                    "- **Check**: Make sure page names match exactly",
                    "",
                    "### Tasks Not Showing",
                    "- **Problem**: Task panel is empty",
                    "- **Solution**: Check that tasks use correct syntax: `- [ ] Task text`",
                    "- **Note**: Tasks must be in Markdown files in your vault",
                    "",
                    "### Calendar Not Showing Dates",
                    "- **Problem**: Calendar panel is empty",
                    "- **Solution**: Ensure dates are in YYYY-MM-DD format",
                    "- **Example**: Use `2025-01-15` not `January 15, 2025`",
                    "",
                    "### AI Features Not Working",
                    "- **Problem**: AI chat or actions fail",
                    "- **Solutions**:",
                    "  - Check API key in preferences",
                    "  - Verify internet connection",
                    "  - Confirm AI is enabled for the vault",
                    "",
                    "### Remote Vault Issues",
                    "- **Problem**: Can't connect to remote vault",
                    "- **Solutions**:",
                    "  - Check server URL and credentials",
                    "  - Verify network connectivity",
                    "  - Check server logs for errors",
                    "",
                    "## Resetting Everything",
                    "If problems persist:",
                    "1. Close the app",
                    "2. Delete the config file (location shown in preferences)",
                    "3. Restart the app (it will create default settings)",
                    "",
                    "## Getting Help",
                    "- Check the [GitHub issues](https://github.com/your-repo/issues) for known problems",
                    "- Include your OS, app version, and error messages when reporting",
                    "",
                    "## Tips",
                    "- Keep your vault folder accessible and not heavily nested",
                    "- Regular backups prevent data loss",
                    "- Test features on small vaults first",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Remote Vaults"),
            title="Remote Vaults",
            content="\n".join(
                [
                    "# Remote Vaults",
                    "",
                    "## What Are Remote Vaults?",
                    "Remote vaults let you access your notes from anywhere.",
                    "- Your notes are stored on a server instead of just locally.",
                    "- Access the same vault from multiple devices.",
                    "- Collaborate with others (if server allows).",
                    "",
                    "## Setting Up a Remote Vault",
                    "1. **Start the Server**: Run StillPoint with `--server` flag",
                    "2. **Configure Access**: Set up authentication on the server",
                    "3. **Connect Client**: Use File → Open Remote Vault in the app",
                    "4. **Enter Details**: Provide server URL and credentials",
                    "",
                    "## Server Setup",
                    "To run your own server:",
                    "```bash",
                    "stillpoint --server --port 8080",
                    "```",
                    "- The server serves your local vault over HTTP.",
                    "- Add `--auth` for password protection.",
                    "- Use `--ssl` for encrypted connections.",
                    "",
                    "## Connecting to a Remote Vault",
                    "- Choose File → Open Remote Vault",
                    "- Enter the server URL (e.g., `http://server.com:8080`)",
                    "- Provide username/password if required",
                    "- The remote vault appears alongside local vaults",
                    "",
                    "## Syncing Changes",
                    "- Changes sync automatically when you save.",
                    "- The server keeps the master copy of your notes.",
                    "- Conflicts are rare but resolved by timestamp.",
                    "",
                    "## Offline Access",
                    "- Remote vaults work when online.",
                    "- Changes are cached locally when offline.",
                    "- Sync resumes when connection returns.",
                    "",
                    "## Security Considerations",
                    "- Use HTTPS for public networks.",
                    "- Choose strong passwords.",
                    "- Keep server software updated.",
                    "- Consider firewall rules for your server.",
                    "",
                    "## Tips",
                    "- Back up your server data regularly.",
                    "- Test connections from different networks.",
                    "- Use remote vaults for shared team notes.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Modes"),
            title="Modes",
            content="\n".join(
                [
                    "# Modes",
                    "",
                    "## What Are Modes?",
                    "Modes change how the interface behaves for different tasks.",
                    "- **Normal Mode**: Full interface with all panels",
                    "- **Focus Mode**: Distraction-free writing",
                    "- **VI Mode**: Vim-style keyboard navigation",
                    "- **Audience Mode**: Presentation view",
                    "",
                    "## Normal Mode",
                    "The default interface:",
                    "- All panels visible (Tasks, Calendar, Links, etc.)",
                    "- Full toolbar and menus",
                    "- Best for general note-taking and organization",
                    "",
                    "## Focus Mode",
                    "For distraction-free writing:",
                    "- Hide all panels except the editor",
                    "- Clean, minimal interface",
                    "- Toggle with View → Focus Mode or Ctrl+Shift+F",
                    "- Perfect for deep writing sessions",
                    "",
                    "## VI Mode",
                    "Vim-style editing:",
                    "- Use keyboard shortcuts for navigation",
                    "- `Esc` to enter command mode",
                    "- `i` to enter insert mode",
                    "- `h/j/k/l` for movement",
                    "- Enable in Preferences → Editor → VI Mode",
                    "",
                    "## Audience Mode",
                    "For presentations:",
                    "- Large, readable text",
                    "- Hide editing controls",
                    "- Navigate with keyboard or mouse",
                    "- Toggle with View → Audience Mode",
                    "",
                    "## Switching Modes",
                    "- Use View menu to switch modes",
                    "- Keyboard shortcuts where available",
                    "- Modes remember their state per vault",
                    "",
                    "## Customizing Modes",
                    "- Some settings can be customized per mode",
                    "- Font sizes may change in Audience mode",
                    "- Panel visibility depends on the mode",
                    "",
                    "## Tips",
                    "- Use Focus mode for creative writing.",
                    "- VI mode is great for power users.",
                    "- Audience mode works well for sharing notes.",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Rendering"),
            title="Rendering",
            content="\n".join(
                [
                    "# Rendering",
                    "",
                    "## What Is Rendering?",
                    "StillPoint can render diagrams and charts from text.",
                    "- **PlantUML**: Create diagrams from simple text",
                    "- **Mermaid**: Flowcharts, Gantt charts, and more",
                    "- **Math**: LaTeX math expressions",
                    "",
                    "## PlantUML Diagrams",
                    "Create diagrams using text:",
                    "```plantuml",
                    "@startuml",
                    "Alice -> Bob: Hello",
                    "Bob --> Alice: Hi there",
                    "@enduml",
                    "```",
                    "- Supports sequence, class, use case, and activity diagrams",
                    "- Diagrams render automatically in the editor",
                    "",
                    "## Mermaid Charts",
                    "Create charts and graphs:",
                    "```mermaid",
                    "graph TD;",
                    "    A-->B;",
                    "    A-->C;",
                    "    B-->D;",
                    "    C-->D;",
                    "```",
                    "- Supports flowcharts, sequence diagrams, Gantt charts",
                    "- Pie charts, git graphs, and state diagrams",
                    "",
                    "## Math Expressions",
                    "Render mathematical formulas:",
                    "```math",
                    "E = mc^2",
                    "```",
                    "Or inline: $E = mc^2$",
                    "- Uses LaTeX syntax",
                    "- Supports fractions, integrals, matrices, etc.",
                    "",
                    "## Code Blocks",
                    "Syntax highlighting for code:",
                    "```python",
                    "def hello():",
                    "    print('Hello, world!')",
                    "```",
                    "- Supports many programming languages",
                    "- Line numbers and copy buttons",
                    "",
                    "## Tables",
                    "Create formatted tables:",
                    "| Header 1 | Header 2 |",
                    "|----------|----------|",
                    "| Cell 1   | Cell 2   |",
                    "| Cell 3   | Cell 4   |",
                    "",
                    "## Enabling Rendering",
                    "- Rendering is enabled by default",
                    "- Check Preferences if diagrams don't appear",
                    "- Some features require internet for rendering",
                    "",
                    "## Tips",
                    "- Use PlantUML for technical diagrams",
                    "- Mermaid is great for flowcharts and processes",
                    "- Math expressions work in both blocks and inline",
                    "- Tables help organize structured data",
                ]
            ),
        )
    )

    pages.append(
        HelpPage(
            name=_page("Web Client"),
            title="Web Client",
            content="\n".join(
                [
                    "# Web Client",
                    "",
                    "## What Is the Web Client?",
                    "Access your notes from any web browser.",
                    "- Run StillPoint as a web server",
                    "- Access from phones, tablets, or other computers",
                    "- Same features as the desktop app",
                    "",
                    "## Starting the Web Server",
                    "Run StillPoint with web client enabled:",
                    "```bash",
                    "stillpoint --web --port 3000",
                    "```",
                    "- Opens a web interface on the specified port",
                    "- Access at `http://localhost:3000`",
                    "",
                    "## Features in Web Client",
                    "- Full note editing with Markdown",
                    "- Task management and calendar",
                    "- Search across all notes",
                    "- AI chat (if configured)",
                    "- Responsive design for mobile devices",
                    "",
                    "## Accessing from Other Devices",
                    "1. Start the web server on your main computer",
                    "2. Find your computer's IP address",
                    "3. On another device, open browser to: `http://IP_ADDRESS:3000`",
                    "4. Use the same interface as on desktop",
                    "",
                    "## Security Considerations",
                    "- Web client runs on your local network by default",
                    "- For remote access, use VPN or secure tunnel",
                    "- No authentication by default - add `--auth` flag",
                    "- Consider firewall settings",
                    "",
                    "## Mobile Access",
                    "- Optimized for touch devices",
                    "- Swipe gestures for navigation",
                    "- Keyboard shortcuts work on mobile browsers",
                    "- Syncs changes across devices",
                    "",
                    "## Differences from Desktop",
                    "- Some file operations may be limited",
                    "- Drag-and-drop works in modern browsers",
                    "- Performance depends on network speed",
                    "",
                    "## Tips",
                    "- Use for quick access from mobile devices",
                    "- Great for sharing notes with others locally",
                    "- Combine with remote vaults for full access anywhere",
                    "- Check browser compatibility for best experience",
                ]
            ),
        )
    )

    return pages


def _write_page(root: Path, page: HelpPage) -> None:
    path = root / page.name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(page.content.strip() + "\n", encoding="utf-8")


def main() -> None:
    root = Path(__file__).resolve().parents[1] / "help-vault"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True, exist_ok=True)

    pages = _build_pages()
    for page in pages:
        _write_page(root, page)

    print(f"Wrote {len(pages)} help pages to {root}")


if __name__ == "__main__":
    main()
